"""SE3 Progress tracking — auto-generated progress entries.

Replaces manual progress.md maintenance. Progress entries are appended
automatically by se3 commit and se3 handoff.

Two granularity levels:
- commit: one-line record appended to "Current Session" section
- session: full session summary generated by se3 handoff
"""

import subprocess
from datetime import datetime
from pathlib import Path
from typing import List, Optional


# Marker for the current session section in progress.md
CURRENT_SESSION_HEADER = "## Current Session"
CURRENT_SESSION_MARKER = "<!-- current-session -->"


def get_git_info(project_root: Path) -> dict:
    """Get current git state."""
    info = {"branch": "unknown", "hash": "unknown", "message": ""}

    result = subprocess.run(
        ["git", "branch", "--show-current"],
        cwd=project_root, capture_output=True, text=True
    )
    if result.returncode == 0 and result.stdout.strip():
        info["branch"] = result.stdout.strip()

    result = subprocess.run(
        ["git", "log", "-1", "--format=%h|%s"],
        cwd=project_root, capture_output=True, text=True
    )
    if result.returncode == 0 and result.stdout.strip():
        parts = result.stdout.strip().split("|", 1)
        info["hash"] = parts[0]
        info["message"] = parts[1] if len(parts) > 1 else ""

    return info


def get_changed_files_count(project_root: Path) -> int:
    """Get the number of files changed in the last commit."""
    result = subprocess.run(
        ["git", "diff-tree", "--no-commit-id", "--name-only", "-r", "HEAD"],
        cwd=project_root, capture_output=True, text=True
    )
    if result.returncode == 0 and result.stdout.strip():
        return len(result.stdout.strip().split("\n"))
    return 0


def ensure_current_session_section(content: str) -> str:
    """Ensure progress.md has a Current Session section at the end.

    Returns the content with the section added if missing.
    """
    if CURRENT_SESSION_MARKER in content:
        return content

    today = datetime.now().strftime("%Y-%m-%d")
    section = f"\n{CURRENT_SESSION_HEADER}\n{CURRENT_SESSION_MARKER}\n\n"

    return content.rstrip() + "\n" + section


def append_commit_entry(project_root: Path) -> bool:
    """Append a commit-level entry to progress.md.

    Called automatically after each successful se3 commit.
    Appends a one-line record to the Current Session section.

    Returns True if successful.
    """
    progress_file = project_root / "progress.md"
    git_info = get_git_info(project_root)
    file_count = get_changed_files_count(project_root)

    entry = f"- `{git_info['hash']}` {git_info['message']} ({file_count} files)\n"

    if progress_file.exists():
        content = progress_file.read_text(encoding="utf-8")
    else:
        today = datetime.now().strftime("%Y-%m-%d")
        content = f"# Progress\n\nCross-session development history. Auto-maintained by SE3 tools.\n\n"

    content = ensure_current_session_section(content)

    # Append entry at the end of the file (after Current Session section)
    content = content.rstrip() + "\n" + entry

    progress_file.write_text(content, encoding="utf-8")
    return True


def get_current_session_entries(project_root: Path) -> List[str]:
    """Extract commit entries from the Current Session section.

    Returns list of commit entry lines.
    """
    progress_file = project_root / "progress.md"
    if not progress_file.exists():
        return []

    content = progress_file.read_text(encoding="utf-8")
    if CURRENT_SESSION_MARKER not in content:
        return []

    # Everything after the marker
    after_marker = content.split(CURRENT_SESSION_MARKER, 1)[1]

    entries = []
    for line in after_marker.split("\n"):
        line = line.strip()
        if line.startswith("- `"):
            entries.append(line)

    return entries


def get_session_diff_stat(project_root: Path, commit_hashes: List[str]) -> str:
    """Get diff stat from first commit to HEAD."""
    if not commit_hashes:
        return "(no commits)"

    first_hash = commit_hashes[0]
    result = subprocess.run(
        ["git", "diff", "--stat", f"{first_hash}~1..HEAD"],
        cwd=project_root, capture_output=True, text=True
    )
    if result.returncode == 0:
        return result.stdout.strip()

    # Fallback: just show HEAD stat
    result = subprocess.run(
        ["git", "diff", "--stat", "HEAD~1..HEAD"],
        cwd=project_root, capture_output=True, text=True
    )
    return result.stdout.strip() if result.returncode == 0 else "(unable to get diff stat)"


def extract_next_steps(project_root: Path) -> str:
    """Extract Next: lines from the last commit message."""
    result = subprocess.run(
        ["git", "log", "-1", "--format=%B"],
        cwd=project_root, capture_output=True, text=True
    )
    if result.returncode != 0:
        return ""

    for line in result.stdout.split("\n"):
        if line.strip().startswith("Next:"):
            return line.strip()[len("Next:"):].strip()
    return ""


def get_session_number(content: str) -> int:
    """Determine the next session number from existing progress.md content."""
    import re
    numbers = re.findall(r"## \d{4}-\d{2}-\d{2} Session (\d+)", content)
    if numbers:
        return max(int(n) for n in numbers) + 1
    return 1


def finalize_session(project_root: Path, done_summary: Optional[str] = None) -> str:
    """Replace Current Session section with a formal session record.

    Called by se3 handoff. Collects commit entries, generates summary,
    and replaces the Current Session section with a dated session record.

    Returns the generated session report text.
    """
    progress_file = project_root / "progress.md"
    if not progress_file.exists():
        return "(no progress.md found)"

    content = progress_file.read_text(encoding="utf-8")
    entries = get_current_session_entries(project_root)

    if not entries:
        return "(no commits in current session)"

    # Extract commit hashes from entries
    import re
    hashes = []
    for entry in entries:
        match = re.match(r"- `([a-f0-9]+)`", entry)
        if match:
            hashes.append(match.group(1))

    today = datetime.now().strftime("%Y-%m-%d")
    session_num = get_session_number(content)
    diff_stat = get_session_diff_stat(project_root, hashes)
    next_steps = extract_next_steps(project_root)

    # Build done summary from commit messages if not provided
    if not done_summary:
        done_lines = []
        for entry in entries:
            # Extract message part: - `hash` message (N files)
            match = re.match(r"- `[a-f0-9]+` (.+) \(\d+ files\)", entry)
            if match:
                done_lines.append(f"- {match.group(1)}")
        done_summary = "\n".join(done_lines) if done_lines else "- (see commits below)"

    # Build session record
    record = f"## {today} Session {session_num} (handoff)\n\n"
    record += f"### Done\n{done_summary}\n\n"
    record += f"### Commits\n"
    for entry in entries:
        record += f"{entry}\n"
    record += f"\n### Files Changed\n```\n{diff_stat}\n```\n\n"
    if next_steps:
        record += f"### Next Steps\n- {next_steps}\n\n"

    # Replace Current Session section with the record
    if CURRENT_SESSION_MARKER in content:
        before_marker = content.split(CURRENT_SESSION_HEADER, 1)[0]
        new_content = before_marker.rstrip() + "\n\n" + record
        # Add empty Current Session section for next session
        new_content += f"\n{CURRENT_SESSION_HEADER}\n{CURRENT_SESSION_MARKER}\n\n"
    else:
        new_content = content.rstrip() + "\n\n" + record

    progress_file.write_text(new_content, encoding="utf-8")
    return record


def append_collab_report(project_root: Path, report: str) -> bool:
    """Append a collab completion report to progress.md.

    Called by collab-orchestrator do_complete().

    Returns True if successful.
    """
    progress_file = project_root / "progress.md"

    if progress_file.exists():
        content = progress_file.read_text(encoding="utf-8")
    else:
        content = "# Progress\n\nCross-session development history. Auto-maintained by SE3 tools.\n\n"

    # Insert the report before the Current Session section if it exists
    if CURRENT_SESSION_HEADER in content:
        before = content.split(CURRENT_SESSION_HEADER, 1)[0]
        after = CURRENT_SESSION_HEADER + content.split(CURRENT_SESSION_HEADER, 1)[1]
        content = before.rstrip() + "\n\n" + report + "\n\n" + after
    else:
        content = content.rstrip() + "\n\n" + report + "\n"

    progress_file.write_text(content, encoding="utf-8")
    return True
