Looking at the conflicts, I need to determine which design won. The **non-conflicting** `FlowInstance.from_dict` (shared code below the conflicts) has signature `from_dict(cls, data, cold_loader=None)` and calls `State.from_dict(data.get("state", {}), cold_loader)` — threading `cold_loader`. This is the G4 (HEAD) design. The G7 `State.from_dict` takes no `cold_loader` and would break that shared call. So the file must be resolved consistently to the **HEAD/G4** design throughout.Resolved the conflict in `src/se3/engine/models.py`.

**Resolution decision:** I chose the **G4 (HEAD)** design consistently across all conflicts, because the file's own non-conflicting code forces it. The shared `FlowInstance.from_dict` has signature `from_dict(cls, data, cold_loader=None)` and calls `State.from_dict(data.get("state", {}), cold_loader)` — threading a `cold_loader`. The G7 variant's `State.from_dict` takes no `cold_loader`, so adopting it would break that already-merged call. G4's cold-loader-threaded design is the only one consistent with the surviving shared code.

Concretely, the merged file uses the G4 hot/cold vocabulary throughout:
- `Step.extract_cold()` / `cold_content_hash()` / `to_header_dict()` (emits `cold_ref` + `content_hash`), `_apply_cold()`, and `from_dict(data, cold_loader)` detecting `cold_ref`.
- `State.extract_cold_context()` / `extract_cold_payloads()` (keyed by `CONTEXT_COLD_KEY`), `to_header_dict()` (emits `context_ref` + `context_hash`), `rehydrate()`, and `from_dict(data, cold_loader)` routing on `context_ref`.
- `FlowInstance.to_header_dict()` emitting the `HOT_COLD_FORMAT` marker and threading `cold_loader` through `from_dict`.

I also made the inline (old-format) branch of `State.from_dict` pass `cold_loader` to `Step.from_dict` for consistency (harmless — inline steps carry no `cold_ref`, so the loader is never invoked there). The `ENGINE_FORMAT_SPLIT` constant from G7 is retained at module level (both branches defined it identically). No conflict markers remain.

Note: the other conflicted files (`persistence.py`, `aggregator.py`, `history.py`, `disk_json_cache.py`) must be resolved to the same cold-loader design for the merge to be coherent — `persistence.py` in particular must bind and pass `ColdLoader` callbacks into `FlowInstance.from_dict`. Those weren't in scope for this file, but they need the matching resolution.